### ISSUE TITLE
Script assumes black background

### ISSUE THREAD

**Issue by dimaqq** [gawin/bash-colors-256#1]
2 problems with this:
1. first two lines of output look weird on white background
2. sript leaves terminal with black background after it exits

**Comment by gawin** [comment]
Thank you for your feedback @dimaqq

That sure is a good suggestion, I've updated the code to respect your original background color ;-)

![fixed-background-color](https://cloud.githubusercontent.com/assets/25894/11869610/6fe5e676-a4c1-11e5-9652-288cffd97541.png)
